services:
  backend:
    build: ./api/backend
    ports:
      - "8080:8080"
    environment:
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=gimnasio
    depends_on:
      - db
  frontend:
    build: ./api/frontend
    ports:
      - "3000:3000"
    depends_on: 
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gimnasio
    ports:
      - "3307:3306"
    volumes: 
      - db-data:/var/lib/mysql

volumes:
  db-data:

 
    
 
        
    
  
